# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

# bugs out in emacs vterm
# right side of prompt
# right_format = """$time"""
# [time]
# disabled = false
# format = 'ðŸ•™[$time]($style) '
# time_format = '%T'

[character]
success_symbol = '[->](bold black)'
error_symbol = '[->](bold red)'


[directory]
style = 'bold black'

[memory_usage]
disabled = false
threshold = 80

[line_break]
disabled = true

[[battery.display]]
threshold = 20
style = 'bold red'

[cmd_duration]
disabled = true

