# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# right side of prompt
right_format = """$time"""

add_newline = false

[time]
disabled = false
format = 'ğŸ•™[$time]($style) '
#format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'


# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'


[memory_usage]
disabled = false
threshold = 80

[line_break]
disabled = true

[cmd_duration]
disabled = true

